language: node_js
node_js:
- node
deploy:
  provider: heroku
  app: immense-inlet-10371
  api_key:
    secure: PNZcNsR/hTzLWb56DWc8MKKEcmt7GZiVHXhfj/53VQy4a7RWPbtF1wwc0frmDyOAWU4Xe4EJqIrCqBadn2VHQNSspSUm4p6rZB4+HFGl7moPr+F4JFAvIkBpxk6WfUYOzG1zize1HWyKRNezATi75DWAk16L+9mKvEopMVJZ8cItagYg/VxtBGaDLdJehIOKq8VW2K37biB8sN15+dXPwIcWWsjTkpaixO9kOwaLEtV3o6BTgDQvpsuW0Qd7JIXjgxxZS3gMoNuAqc8myaUPzV1YVatcjxdqrRlns7r1Dk2CIp5lqC+a/YdXs10TFd4osk+NDm/sr21RR8rIWl/73CcfJRXQrJ2856ZOQEgexGh2vKBgHDN2HCQ+XVQKuyK6KOXqNUJOQbdATb5i7kP+bfiC+4s0//8ITOh4ISJaHSzKpWWZfThIe+JHZ0H4ODjhqpnBNap7s3Pa43B/iLUZpvRrR3xl3MRC6oONWQmaEjN3KmCfMoh7tACQTIAN9rpSpSNPrRarLhCxXoU9Lwk8AkvMYkeQRHggM/VkYqE0TmY4jUpcAqiIFxr5MV6YxclzKO+r4/YXyVMMuMEle0qj2zlI6dlMsKDUoo6pYavumHSWzOXd5JaTN6Htt1H+b/+l4raCHwbIh7nK3JZE83SpEU/Rw2Qy+7BCW9hSQTE9xwI=
