language: node_js
node_js:
  - node
deploy:
  provider: heroku
  app: immense-inlet-10371
  api_key:
    secure: G02N7MrLsD8VA8LjYQeTmnx8x7Da/gzg6e5LYOCZFzIJkmxwkbE+PZWQ0r/RgXoUEgD3XF7UQUtz9wF6K2VGm96c2JLNcCzkAO5UKw4EX4qAiJ5UCNEwWZsieezNnsfrV/pt+aIlU88iqJ57UMmQDN4D3mMIi/p8IXTBJuP9c5VPsLiV5lGJB0c9WeCtoZqu2trg9HM/pYtyeRTG/8IpKTY3ybMJhCUND/PDX6XWYtgumOU762yG34p8241lI4sePmGZ8pHiP7WLKGy0EzCbaebFbuphY/DTIm0HHRBCmDorUcRHP9kA0/lhhwADPkvy6zT0w0R8Ner1ho3piatdBrAjlIiIa4DHFSFlSt2G0XAxh23DxQnTYK7n3yuBn/6AghxSlPevHgM144gopT6OaVyDQKdL1Jix6MNbf+mxcdNaMNnbSgmvR3YRKBUz0c+2lwzFPhM3m6zKSBLcV/Lpef8THGuVkAZTxCyLYyBHBprDSHqobsCCtjqE7aG3La33Ul9HXHnj+C7gnUdC7+voeONQSPTzw4OKffdSn+6KWo6uCI8/BcoDrvYhDl+IzJ6KNvdQsU+VnpcueijoFNfTpUn0FNizW6AnhUtD0psL9Q/12K9mruOB+/8xkhD0IQrqbxydVcyfs/wmx/Dir7hUNC+p7xR/iSO8N5h5vrut9fw=
