language: node_js
node_js:
- node
deploy:
  provider: heroku
  app: immense-inlet-10371
  api_key:
    secure: AScT7GM+nLpIWkMtjxBEchG8ZsEmHkCFihhxYj53wFAUdvEsYwdqFHII+6qFF5D2oBuhcRP5qnJUVhaEbda21aQsh8Mqxt+d2VVEtIxWEOm5SQyZpGEmjpv0FxWJl+xCgTyusg8ZnQK7mULSd/sy9FXqff0hSvcCXRbdUo3K5gq1MNeb7E6uaSMAcPpeDHgGBbP1ap4Mu0zrC2LxB2qCko1CxZ47Tuyhb3I+G+TJcPWCrtLVzJGffFILuGZgABwDD25dolhoIyboJNvlFCqnHAP8/c0bWRm5DXhFw37eY3gfr0mMfNxGl0ImeP0yFysjwABHgA3XTMnJ5XF2OFcfCuTD+EUKGcg0g9X59IKh5AuqEV84tzknZczqnqRge/FX4XXwarjU53C9RqwlGwalk5F2q92nqhEfltqXdLIloFtTCECpogFmcxbgSTUY/G/9/LhIhpH5q0zIjUMZXAZlY2Nx4JdcBwmcjM4V2lo8ETQ8X82dBn7hOQzVrR4VQRZ9Um+6Ktbmuw+lT8wD0i1RJNhH9hbgFW6Zo0Rx/mW11t9xYcKgFxnW+xFBE9TwPgJboVIO9rfgGASgmV+PjfXDxeXH3L8NNNC77kHmzyx9pu4Xc3TVWzntviskdNfZUsPODNYhNqcUdjlYyBA1TsPMm2i4jCBbjhiSxZqs+TfKeeQ=
